### ISSUE TITLE
Please provide for download

### ISSUE THREAD

**Issue by probonopd** [nlordell/aseprite-appimage#1]
Please provide it for download on https://github.com/nlordell/aseprite-appimage/releases, thank you.

**Comment by nlordell** [comment]
This is not permitted by the Aseprite license.

From the [EULA](https://github.com/aseprite/aseprite/blob/main/EULA.txt):

> You may not distribute copies of the SOFTWARE PRODUCT to third parties.

And from the [Aseprite FAQ](https://www.aseprite.org/faq/#can-i-redistribute-aseprite):

> No. From August 2016 you cannot redistribute compiled versions of Aseprite. We have replaced the General Public License (GPLv2) with the new Aseprite EULA. The only way to redistribute Aseprite is with an special educational license.
>
> Anyway this does not restrict most users: You can still compile the source code, and use the program to create your assets for commercial games. You can also make contributions to Aseprite or modify its source code for your personal purposes.

**Comment by probonopd** [comment]
> We have replaced the General Public License (GPLv2) with the new Aseprite EULA. 

Sorry, I wasn't aware of this. Hope the original author will put out an AppImage.
